name: myapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  # firebase_auth:
  # cloud_firestore:
  # google_sign_in:
  # flutter_facebook_login:
  flutter:
    sdk: flutter
  sqflite: any
  path_provider: ^1.5.1
  intl: ^0.16.0
  url_launcher: ^5.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # firebase_core: ^0.4.0+9
  # firebase_analytics: ^1.1.0
  # firebase_auth: 0.14.0+5
  # cloud_firestore: ^0.12.9+4
  # image_picker: ^0.6.1+4
  # cached_network_image: ^2.0.0-rc
  # firebase_storage: ^3.0.6  
  # # path_provider: ^1.5.1
  # flutter_image_compress: ^0.6.3
  # uuid: ^2.0.2
  # provider: ^3.2.0
  # image_cropper: ^1.1.0
  # animator: ^1.0.0+3
  http: ^0.12.0+1
  # webfeed: ^0.4.2
  # cached_network_image: ^1.0.0
  # transparent_image: ^1.0.0
  youtube_player_flutter: ^6.0.3+2
  # flutter_linkify: 1.0.3
  youtube_api: ^0.7.2
  youtube_player: ^3.5.0
  shared_preferences: ^0.5.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
  twitter_api: ^0.1.2
  # video_player: ^0.10.1
  # chewie: ^0.9.7   
  # font_awesome_flutter: ^8.5.0
  # shadow: ^0.1.5
  # flutter_share_me: ^0.4.0
  # image_picker: 0.6.2+1
  # social_share_plugin: ^0.2.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   #- images/money.png   
  #  - videos/Kamma_Rajyam_Lo_Kadapa_Reddlu_TRAILER.mp4
  #  - images/blue.jpg
  #  - images/user_placeholder.jpg
   - images/
   - images/blue.jpg
   - images/plansbg.png
   - images/rgv_image.jpg
   - images/Ram_Gopal_Varma.webp
   - images/ram-gopal-varma.gif
   - images/TH-7-STAR-RGV.jpeg   
   - images/shivamovie.jpg
   - images/kshanakshanam.jpg   
   - images/gaayam.jpg
   - images/govinda.jpg
   - images/Rangeela.jpg
   - images/great.jpg   
   - images/satya.jpg
   - images/dilse.jpg
   - images/mast.jpg
   - images/shool.jpg
   - images/Jungle.jpg
   - images/Company.jpg
   - images/Road.jpg
   - images/Bhoot.jpg
   - images/darna.jpg
   - images/Ek.jpg   
   - images/Ab.jpg
   - images/gayab.jpg
   - images/Vaastu_Shastra.jpg
   - images/Naach.jpg   
   - images/mr_miss.jpg
   - images/Sarkar.jpg
   - images/murder.jpg
   - images/Darna_Zarrori.jpg 
   - images/Darwaza.jpg
   - images/Nishabd.jpg
   - images/RGV_Ki_Aag.png
   - images/Go.jpg
   - images/sarkar-raj.jpg
   - images/contract-movie.jpg
   - images/Phoonk.jpg
   - images/adavi_movie.jpg   
   - images/Drohi.jpg
   - images/Rakhta_Charitra.jpg
   - images/Rakhta_Charitra2.jpg
   - images/KSD_Appalaraju.jpg   
   - images/Dongala_muta.jpg
   - images/Not_a_lovestory.jpg
   - images/Shabri.jpg
   - images/Department_movie_poster.jpg
   - images/Boochi_movie.jpg
   - images/Attack.jpg
   - images/psycho-telugu.jpg
   - images/Rowdy.jpg
   - images/Patta_pagalu.jpg
   - images/Icream.jpg
   - images/Anukshanam.jpg
   - images/Icream2.jpg
   - images/days365.jpg
   - images/Mogali.jpg
   - images/Killing_veerappan.jpg
   - images/chocobar-movie.png
   - images/Vangaveeti.jpg
   - images/Sarkar-3.jpg
   - images/Officer.jpg
   - images/Bhairava_Geetha.jpg
   - images/NTR.jpg
   - images/cobra-et.jpg
   - images/Amma_Rajyam_Lo_Kadapa_Biddalu.jpg
   - images/R0.jpg
   - images/R1.jpg
   - images/R2.jpg
   - images/R3.jpg
   - images/R4.jpg
   - images/R5.jpg
   - images/R6.jpg
   - images/R7.jpg
   - images/R8.jpg
   - images/R9.jpg
   - images/R10.jpg
   - images/R11.jpg
   - images/R12.jpg
   - images/R13.jpg
   - images/R14.jpg
   - images/R15.jpg
   - images/R16.jpg
   - images/R17.jpg
   - images/R18.jpg
   - images/R19.jpg
   - images/R20.jpg
   - images/R21.jpg
   - images/R22.jpg
   - images/R23.jpg
   - images/R24.jpg
   - images/R25.jpg
   - images/R26.jpg
   - images/R27.jpg
   - images/R28.jpg
   - images/R29.jpg
  #  - images/ypf.png
  #  - images/R2.jpg
  #  - images/R2.jpg

   
  # assets:
  #  - videos/flutter_dart_v.mp4


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Twitter
      fonts:
        - asset: fonts/icon_twitter.ttf
    - family: Instagram
      fonts:
        - asset: fonts/icon_instagram.ttf  
    - family: Facebook
      fonts:
        - asset: fonts/icon_facebook.ttf         
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
 















